---

- name: Check connection to consul backend
  wait_for: host={{ nginx_docker_consul_host }} port={{ nginx_docker_consul_port }} timeout=60

- name: Create nginx servers config
  template: 
    src:  nginx-server.conf.j2 
    dest: "{{ nginx_docker_conf_dir }}/servers/{{ nginx_docker_conf_name }}.conf"

- name: Create consul-template templates of nginx include and upstream config for service
  template:
    src:  nginx-{{ item }}.conf.ctmpl.j2
    dest: "{{ nginx_docker_templates[item].ctmpl }}"
  with_items:
    - include
    - upstream

- name: Render consul-template templates of nginx include and upstream config for service
  shell: >
    consul-template \
      -consul "{{ nginx_docker_consul_host }}:{{ nginx_docker_consul_port }}" \
      -template "{{ item.value.ctmpl }}:{{ item.value.conf }}:docker kill -s HUP nginx" \
      -once
  with_dict: "{{ nginx_docker_templates }}"
