---

- name: Create nginx directories
  file: path="{{ item }}" state=directory
  with_items: "{{ nginx_docker_dirs }}"

- name: Start nginx container
  docker:
    name:  nginx
    image: nginx
    state: running
    ports: "{{ nginx_docker_ports }}"
    volumes: "{{ nginx_docker_volumes }}"

- name: Create nginx services config files
  template: src=services.conf.j2 dest="{{ nginx_docker_conf_dir }}/conf.d/services.conf"
  register: result

- name: Restart nginx container
  shell: docker kill -s HUP nginx
  when: result|changed

- debug: msg="Container name & port - {{ nginx_docker_container_name }}:{{ nginx_docker_container_port }}"

- name: Add nginx config for service
  include: add_service.yml
  when: nginx_docker_container_name|default(false) and not nginx_docker_remove_service

- name: Remove nginx config for service
  include: remove_service.yml
  when: nginx_docker_remove_service
