---

- name: Create nginx servers config
  template: 
    src:  nginx-server.conf.j2 
    dest: "{{ nginx_docker_conf_dir }}/servers/{{ nginx_docker_conf_name }}.conf"

## - name: Create nginx includes Consul template
##   template:
##     src:  nginx-include.conf.ctmpl.j2
##     dest: "{{ nginx_docker_conf_dir }}/templates/{{ nginx_docker_service_name }}-include.conf.ctmpl"
## 
## - name: Create nginx-upstreams Consul template
##   template:
##     src:  nginx-upstream.conf.ctmpl.j2
##     dest: "{{ nginx_docker_conf_dir }}/templates/{{ nginx_docker_service_name }}-upstream.conf.ctmpl"

- name: Create nginx config Consul template
  template:
    src:  nginx-{{ item }}.conf.ctmpl.j2
    dest: "{{ nginx_docker_templates[item].ctmpl }}"
  with_items:
    - include
    - upstream

- name: Apply nginx-includes Consul templates are applied
  shell: >
    consul-template \
      -consul "{{ nginx_docker_consul_host }}:{{ nginx_docker_consul_port }}" \
      -template "{{ item.value.ctmpl }}:{{ item.value.conf }}:docker kill -s HUP nginx" \
      -once
  with_dict: "{{ nginx_docker_templates }}"
